CREATE TABLE IF NOT EXISTS mpa (
                                   mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
                                      genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                         film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(250) UNIQUE NOT NULL,
                         description varchar(250) NOT NULL,
                         release_date DATE,
                         duration INTEGER,
                         mpa_id BIGINT REFERENCES mpa(mpa_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
                         user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email varchar(255) UNIQUE NOT NULL,
                         login varchar(255) NOT NULL,
                         name varchar(255),
                         birthday DATE
);

CREATE TABLE IF NOT EXISTS films_genres (
                               genre_id BIGINT REFERENCES genres(genre_id) ON DELETE CASCADE,
                               film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
                           user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
                           friend_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
                           isConfirm bool NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS likes (
                         user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
                         film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE
);



