CREATE TABLE IF NOT EXISTS mpa (
                                   mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
                                      genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar(250) NOT NULL,
                                     description varchar(250) NOT NULL,
                                     release_date DATE,
                                     duration INTEGER,
                                     mpa_id BIGINT
);

CREATE TABLE IF NOT EXISTS films_genres (
                                            film_id BIGINT NOT NULL,
                                            genre_id BIGINT NOT NULL,
                                            PRIMARY KEY (film_id, genre_id),
                                            FOREIGN KEY(film_id) REFERENCES films(film_id),
                                            FOREIGN KEY(genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email varchar(255) UNIQUE NOT NULL,
                                     login varchar(255) NOT NULL,
                                     name varchar(255),
                                     birthday DATE
);

CREATE TABLE IF NOT EXISTS friends (
                                       user_id BIGINT NOT NULL,
                                       friend_id BIGINT NOT NULL,
                                       isConfirm bool NOT NULL DEFAULT false,
                                       PRIMARY KEY (user_id, friend_id),
                                       FOREIGN KEY(user_id) REFERENCES users(user_id),
                                       FOREIGN KEY(friend_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS likes (
                                     user_id BIGINT NOT NULL,
                                     film_id BIGINT NOT NULL,
                                     PRIMARY KEY (user_id, film_id),
                                     FOREIGN KEY(film_id) REFERENCES films(film_id),
                                     FOREIGN KEY(user_id) REFERENCES users(user_id)

);

CREATE TABLE IF NOT EXISTS directors (
    director_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_directors (
    film_id BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, director_id),
    FOREIGN KEY(film_id) REFERENCES films(film_id),
    FOREIGN KEY(director_id) REFERENCES directors(director_id)
);

INSERT INTO directors (director_id, name)
VALUES
    (1, 'Стенли Кубрик'),
    (2, 'Квентин Тарантино'),
    (3, 'Мартин Скорсезе');
    (4, 'Джеймс Кэмерон');
    (5, 'Джордж Лукас');