CREATE TABLE "FILMS" (
                         "FILM_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "NAME" varchar UNIQUE NOT NULL,
                         "DESCRIPTION" text NOT NULL,
                         "RELEASE_DATE" date,
                         "DURATION" interval,
                         "MPA_ID" INT
);

CREATE TABLE "USERS" (
                         "USER_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "EMAIL" varchar UNIQUE NOT NULL,
                         "LOGIN" varchar NOT NULL,
                         "NAME" varchar,
                         "BIRTHDAY" date
);

CREATE TABLE "FILMS_GENRE" (
                               "GENRE_ID" integer,
                               "FILM_ID" integer
);

CREATE TABLE "GENRE" (
                         "GENRE_ID" integer,
                         "NAME" varchar NOT NULL
);

CREATE TABLE "FRIENDS" (
                           "USER_ID" integer,
                           "FRIEND_ID" integer,
                           "CONFIRMED" bool NOT NULL DEFAULT false
);

CREATE TABLE "LIKES" (
                         "USER_ID" integer,
                         "FILM_ID" integer
);

CREATE TABLE "MPA" (
                       "MPA_ID" integer PRIMARY KEY,
                       "NAME" VARCHAR NOT NULL
);

COMMENT ON COLUMN "FRIENDS"."CONFIRMED" IS 'true = подтверждено, false = ожидает подтверждения';

ALTER TABLE "FILMS" ADD FOREIGN KEY ("MPA_ID") REFERENCES "MPA" ("MPA_ID");

ALTER TABLE "FILMS_GENRE" ADD FOREIGN KEY ("FILM_ID") REFERENCES "FILMS" ("FILM_ID");

ALTER TABLE "FILMS_GENRE" ADD FOREIGN KEY ("GENRE_ID") REFERENCES "GENRE" ("GENRE_ID");

ALTER TABLE "FRIENDS" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "FRIENDS" ADD FOREIGN KEY ("FRIEND_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "LIKES" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "LIKES" ADD FOREIGN KEY ("FILM_ID") REFERENCES "FILMS" ("FILM_ID");
